'use client';

import { useEffect, useRef, useState, type ReactNode } from 'react';
import { flushSync } from 'react-dom';
import { ArrowRight, ArrowUpRight, BedDouble, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Copy, Inbox, MapPin, Moon, Plus, RotateCcw, Smartphone, Monitor, TrainFront, Utensils, Plane, Users, Music2, SlidersHorizontal, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

type Kind = 'food' | 'travel' | 'stay' | 'social' | 'appointment';
type Plan = { zoneLabel?:string; id:string; title:string; short:string; date:string; endDate?:string; time?:string; endTime?:string; kind:Kind; location:string; detail:string; reference?:string; source:string };
type Suggestion = { id:string; plan:Plan; status:string; excerpt:string; action:string; needsDate?:boolean };
const studies = [
 { id:'contour', name:'Contour', letter:'A', description:'Fine lines. A full month. Everything in its place.', focus:'Precise grid · attached day panel', color:'#A8C6EB' },
 { id:'margin', name:'Margin', letter:'B', description:'A little more room for the things you look forward to.', focus:'Open month · expressive type · bottom agenda', color:'#CAD5DF' },
 { id:'gather', name:'Gather', letter:'C', description:'A softer shape for your month.', focus:'Tactile dates · periwinkle · centred layout', color:'#BEC5FF' },
 { id:'field', name:'Field', letter:'D', description:'Quietly organised, down to the small details.', focus:'Compact grid · mint · horizontal detail dock', color:'#B7D5C6' },
 { id:'ember', name:'Ember', letter:'E', description:'Make room for a good September.', focus:'Warm charcoal · week bands · spacious day panel', color:'#D9B784' },
 { id:'air', name:'Air', letter:'F', description:'Field, with more space to breathe.', focus:'Field / spacious month + lower agenda', color:'#B9D6C7' },
 { id:'focus', name:'Focus', letter:'G', description:'The month and its details, comfortably side by side.', focus:'Field / quiet day sidebar', color:'#ACCBBE' },
 { id:'flow', name:'Flow', letter:'H', description:'See the month. Read the week.', focus:'Field / month + week agenda', color:'#AFCFD1' },
 { id:'slate', name:'Slate', letter:'I', description:'Contour with less chrome and clearer details.', focus:'Contour / streamlined navigation', color:'#AEC8E7' },
 { id:'edge', name:'Edge', letter:'J', description:'Give the month the room. Bring details closer.', focus:'Contour / full-width month + dismissible details', color:'#BAD5CE' },
];
const initialPlans:Plan[] = [
 {id:'luca',title:'Dinner at Luca',short:'Luca',date:'2026-09-08',time:'19:30',endTime:'21:00',kind:'food',location:'88 St John Street, London',detail:'A table for two. The sample reservation includes a 90-minute table.',reference:'DEMO-LUCA',source:'Gmail'},
 {id:'train',title:'Train to Edinburgh',short:'Edinburgh',date:'2026-09-11',time:'17:30',endTime:'21:52',kind:'travel',location:"London King's Cross → Edinburgh Waverley",detail:'Coach C · seats 21 & 22 · Europe/London. Fictional journey times.',reference:'DEMO-RAIL',source:'Gmail'},
 {id:'hotel',title:'A weekend at The Rowan',short:'The Rowan',date:'2026-09-11',endDate:'2026-09-13',kind:'stay',location:'Edinburgh',detail:'Two nights · 11–13 September. Check-in and checkout times were not supplied.',reference:'DEMO-ROWAN',source:'Gmail'},
 {id:'coffee',title:'Coffee with Maya',short:'Coffee',date:'2026-09-16',time:'10:00',kind:'social',location:'Clerkenwell, London',detail:'A catch-up over coffee. End time not supplied.',source:'WhatsApp'},
 {id:'market',title:'Broadway Market',short:'Market',date:'2026-09-19',time:'10:30',kind:'social',location:'London Fields, London',detail:'Meeting Ben by the flower stall.',source:'Manual'},
 {id:'tennis',title:'Tennis with Ollie',short:'Tennis',date:'2026-09-19',time:'14:00',endTime:'15:30',kind:'social',location:'Highbury Fields · Court 3',detail:'Court booked for 90 minutes.',source:'Gmail'},
 {id:'priya',title:'Dinner with Priya',short:'Dinner',date:'2026-09-19',time:'18:00',endTime:'19:30',kind:'food',location:'Islington, London',detail:'Dinner before heading out for the evening.',source:'WhatsApp'},
 {id:'flight-out',title:'Flight to Copenhagen',short:'Copenhagen',date:'2026-09-22',time:'09:20',zoneLabel:'London',kind:'travel',location:'London Heathrow → Copenhagen',detail:'09:20 London → 12:15 Copenhagen · 1h 55m. Times are local to each airport. Fictional itinerary.',reference:'DEMO-CPH',source:'Gmail'},
 {id:'flight-back',title:'Flight home',short:'London',date:'2026-09-24',time:'18:45',zoneLabel:'Copenhagen',kind:'travel',location:'Copenhagen → London Heathrow',detail:'18:45 Copenhagen → 19:40 London · 1h 55m. Times are local to each airport. Fictional itinerary.',reference:'DEMO-CPH',source:'Gmail'},
 {id:'concert',title:'Live at the Roundhouse',short:'Roundhouse',date:'2026-09-26',time:'19:00',kind:'social',location:'Roundhouse, Camden',detail:'Two tickets · doors at 19:00. Show end time not supplied.',reference:'DEMO-LIVE',source:'Gmail'},
 {id:'dentist',title:'Dentist',short:'Dentist',date:'2026-09-29',time:'08:45',endTime:'09:15',kind:'appointment',location:'Upper Street, London',detail:'Routine appointment.',source:'Gmail'},
];
const initialSuggestions:Suggestion[] = [
 {id:'party',status:'Invitation · attendance unknown',excerpt:'Birthday drinks at mine on Saturday 19 September, from eight. Would love you to come!',action:"I'm going",plan:{id:'party',title:"Alex's birthday",short:'Birthday',date:'2026-09-19',time:'20:00',kind:'social',location:"Alex's place, London",detail:'Birthday drinks · end time not supplied.',source:'WhatsApp'}},
 {id:'juniper',status:'Booking confirmed · ready to add',excerpt:'Your table for four is confirmed for Thursday 17 September at 19:30. We look forward to welcoming you.',action:'Add to calendar',plan:{id:'juniper',title:'Dinner at Juniper',short:'Juniper',date:'2026-09-17',time:'19:30',kind:'food',location:'Juniper, London',detail:'Table for four · end time not supplied.',reference:'DEMO-JUNIPER',source:'Gmail'}},
 {id:'sam',status:'Date missing',excerpt:'See you tomorrow at eight at Riverside!',action:'Choose date',needsDate:true,plan:{id:'sam',title:'Dinner with Sam',short:'Sam',date:'',time:'20:00',kind:'social',location:'Riverside',detail:'The original message date was not included in the forward.',source:'WhatsApp'}},
];
const weekdays = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const iso = (date:Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const parseDate = (date:string) => new Date(`${date}T12:00:00`);
const formatDate = (date:string, options:Intl.DateTimeFormatOptions = {weekday:'long',day:'numeric',month:'long'}) => parseDate(date).toLocaleDateString('en-GB',options);
function calendarDays(year:number,month:number) { const first=new Date(year,month,1); const start=(first.getDay()+6)%7; const count=Math.ceil((start+new Date(year,month+1,0).getDate())/7)*7; return Array.from({length:count},(_,i)=>new Date(year,month,1-start+i)); }
function dayPlans(plans:Plan[],date:string) {return plans.filter(p=>p.endDate ? date>=p.date && date<=p.endDate : p.date===date).sort((a,b)=>(a.time||'99').localeCompare(b.time||'99'));}
function Icon({kind,title='',size=18}:{kind:Kind;title?:string;size?:number}) {const Comp=kind==='food'?Utensils:kind==='stay'?BedDouble:kind==='travel'?(title.toLowerCase().includes('flight')?Plane:TrainFront):kind==='appointment'?CalendarDays:title.includes('Roundhouse')?Music2:Users;return <Comp size={size} strokeWidth={1.6} aria-hidden="true"/>;}
function Action({children,onClick,primary=false,className='',label}:{children:ReactNode;onClick?:()=>void;primary?:boolean;className?:string;label?:string}){return <Button variant="ghost" className={`${primary?'primary-action':'quiet-action'} ${className}`} onClick={onClick} aria-label={label}>{children}</Button>;}

export default function Home(){
 const [style,setStyle]=useState('air'); const [phone,setPhone]=useState(false);
 const [view,setView]=useState({year:2026,month:8}); const [selected,setSelected]=useState('2026-09-11');
 const [plans,setPlans]=useState<Plan[]>(initialPlans); const [suggestions,setSuggestions]=useState(initialSuggestions);
 const [modal,setModal]=useState<'review'|'event'|'add'|'notes'|'settings'|null>(null); const [active,setActive]=useState<Plan|null>(null);
 const [notice,setNotice]=useState(''); const [dateChoice,setDateChoice]=useState(''); const [draft,setDraft]=useState({title:'',date:'2026-09-11',time:'',location:''});
 const [notes,setNotes]=useState<Record<string,string>>({}); const [liked,setLiked]=useState<string[]>([]);
 const study=studies.find(s=>s.id===style)!;
 const isNew=studies.findIndex(s=>s.id===style)>=5;
 const visibleStudies=isNew?studies.slice(5):studies.slice(0,5);
 const [peekOpen,setPeekOpen]=useState(true);
 const peekCloseRef=useRef<HTMLButtonElement>(null);
 const peekReopenRef=useRef<HTMLButtonElement>(null);
 function togglePeek(open:boolean){flushSync(()=>setPeekOpen(open));(open?peekCloseRef:peekReopenRef).current?.focus();}
 useEffect(()=>{
  type DesignTool = {name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(tool:DesignTool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'show_calendar_design',description:'Show one of the ten fictional calendar mockups for comparison. Does not modify bookings.',inputSchema:{type:'object',properties:{design:{type:'string',enum:studies.map(s=>s.id)}},required:['design'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||!('design' in input)||typeof input.design!=='string'||!studies.some(s=>s.id===input.design))throw new Error(`Choose one of: ${studies.map(s=>s.id).join(', ')}.`);const id=input.design;flushSync(()=>setStyle(id));window.history.replaceState(null,'',`#${id}`);return {design:id,name:studies.find(s=>s.id===id)!.name};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return()=>lifecycle.abort();
 },[]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{const hash=window.location.hash.slice(1); if(studies.some(s=>s.id===hash))setStyle(hash);try{const storedNotes:unknown=JSON.parse(localStorage.getItem('calendar-design-notes')||'{}');const storedLikes:unknown=JSON.parse(localStorage.getItem('calendar-design-likes')||'[]');if(storedNotes&&typeof storedNotes==='object'&&!Array.isArray(storedNotes))setNotes(Object.fromEntries(Object.entries(storedNotes).filter(([key,value])=>studies.some(s=>s.id===key)&&typeof value==='string')));if(Array.isArray(storedLikes))setLiked(storedLikes.filter((id):id is string=>typeof id==='string'&&studies.some(s=>s.id===id)));}catch{}});return()=>cancelAnimationFrame(frame)},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(t)},[notice]);
 function switchStyle(id:string){setStyle(id);setPeekOpen(true);window.history.replaceState(null,'',`#${id}`);}
 function chooseDay(date:string){setSelected(date);if(style==='edge')setPeekOpen(true);const d=parseDate(date);if(d.getMonth()!==view.month||d.getFullYear()!==view.year)setView({month:d.getMonth(),year:d.getFullYear()});}
 function moveMonth(delta:number){const d=new Date(view.year,view.month+delta,1);setView({year:d.getFullYear(),month:d.getMonth()});setSelected(iso(d));}
 function goToday(){setView({year:2026,month:8});setSelected('2026-09-07');}
 function openPlan(plan:Plan){setActive(plan);setModal('event');}
 function openAdd(){setDraft({title:'',date:selected,time:'',location:''});setModal('add');}
 function reset(){setPlans(initialPlans);setSuggestions(initialSuggestions);setView({year:2026,month:8});setSelected('2026-09-11');setDateChoice('');setNotice('Sample plans reset');}
 function accept(s:Suggestion){const p={...s.plan,date:s.needsDate?dateChoice:s.plan.date};if(!p.date)return;setPlans(prev=>prev.some(x=>x.id===p.id)?prev:[...prev,p]);setSuggestions(prev=>prev.filter(x=>x.id!==s.id));chooseDay(p.date);setNotice(`${p.title} added to calendar`);}
 function saveDraft(e:React.SyntheticEvent<HTMLFormElement>){e.preventDefault();if(!draft.title.trim()||!draft.date)return;const p:Plan={id:`manual-${Date.now()}`,title:draft.title.trim(),short:draft.title.trim(),date:draft.date,time:draft.time||undefined,kind:'social',location:draft.location||'Location not supplied',detail:draft.time?'End time not supplied.':'Time not supplied.',source:'Manual'};setPlans(prev=>[...prev,p]);chooseDay(p.date);setModal(null);setNotice('Event added');}
 function saveNote(value:string){const next={...notes,[style]:value};setNotes(next);try{localStorage.setItem('calendar-design-notes',JSON.stringify(next));}catch{}}
 function toggleLike(){const next=liked.includes(style)?liked.filter(x=>x!==style):[...liked,style];setLiked(next);try{localStorage.setItem('calendar-design-likes',JSON.stringify(next));}catch{}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice('Copied')}catch{setNotice('Copy unavailable. Select the text to copy it.')}}
 const entries=dayPlans(plans,selected);
 const total=plans.filter(p=>p.date.startsWith(`${view.year}-${String(view.month+1).padStart(2,'0')}`)).length;
 const days=calendarDays(view.year,view.month);
 const nav=<div className="month-navigation"><Action onClick={()=>moveMonth(-1)} label="Previous month"><ChevronLeft size={18}/></Action><Action onClick={goToday}>Today</Action><Action onClick={()=>moveMonth(1)} label="Next month"><ChevronRight size={18}/></Action></div>;
 const reviewButton=<Action className="review-button" onClick={()=>setModal('review')}><Inbox size={17}/><span>Review</span><b>{suggestions.length}</b></Action>;
 const addButton=<Action primary onClick={openAdd}><Plus size={17}/><span>Add event</span></Action>;
 const brand=<div className="brand"><div className="brand-mark"><CalendarDays size={21} strokeWidth={1.4}/></div><span>{study.name.toLowerCase()}<i>.</i></span></div>;
 const calendar=<div className="calendar" aria-label={`${months[view.month]} ${view.year}`}><div className="weekday-row">{weekdays.map(d=><div key={d}>{d}</div>)}</div><div className="calendar-grid">{days.map((date,i)=>{const key=iso(date);const events=dayPlans(plans,key);const inMonth=date.getMonth()===view.month;return <button key={key} type="button" className={`day-cell ${key===selected?'is-selected':''} ${key==='2026-09-07'?'is-today':''} ${!inMonth?'is-other':''} ${events.length?'is-occupied':''} ${i%7>=5?'is-weekend':''}`} aria-label={`${formatDate(key)}, ${events.length} ${events.length===1?'plan':'plans'}`} aria-pressed={key===selected} onClick={()=>chooseDay(key)}><span className="day-number">{date.getDate()}</span><div className="day-events">{events.slice(0,2).map(p=><div className={`calendar-event kind-${p.kind} ${p.endDate?'is-stay':''} ${p.endDate===key?'is-checkout':''}`} key={p.id}><span className="event-dot"/><span className="event-time">{p.time}{p.zoneLabel==='Copenhagen'?' CPH':''}</span><span className="event-full">{p.endDate===key?'Checkout':p.title}</span><span className="event-short">{p.endDate===key?'Checkout':p.short}</span></div>)}{events.length>2&&<span className="event-overflow">+{events.length-2} more</span>}</div><span className="mobile-event-count">{events.length>1?`${events.length} plans`:events[0]?(events[0].endDate===key?'Checkout':events[0].short):''}</span><div className="day-markers">{events.slice(0,3).map(p=><span key={p.id} className={`marker kind-${p.kind}`}/>)}{events.length>3&&<span className="marker-count">+{events.length-3}</span>}</div></button>})}</div></div>;
 const dayPanel=<section className="day-panel" aria-label="Selected day"><div className="day-heading"><div className="day-large-number">{parseDate(selected).getDate().toString().padStart(2,'0')}</div><div><span className="overline">{formatDate(selected,{weekday:'long'})}</span><h2>{formatDate(selected,{day:'numeric',month:'long'})}</h2><p>{entries.length?`${entries.length} ${entries.length===1?'plan':'plans'} for the day`:'A little breathing room'}</p></div><Action onClick={openAdd} label="Add event to selected day" className="day-add"><Plus size={18}/></Action></div><div className="selected-events">{entries.length?entries.map(p=><button key={p.id} className={`detail-entry kind-${p.kind}`} onClick={()=>openPlan(p)}><span className="detail-icon"><Icon kind={p.kind} title={p.title} size={20}/></span><span className="detail-copy"><span className="detail-time">{p.endDate===selected?'Checkout · time not supplied':p.time?`${p.time}${p.endTime?` – ${p.endTime}`:''}${p.zoneLabel?` · ${p.zoneLabel}`:''}`:p.endDate?'11–13 Sep · 2 nights':'Time not supplied'}</span><strong>{p.title}</strong><span className="detail-location">{p.location}</span></span><ArrowUpRight className="detail-arrow" size={17}/></button>):<div className="empty-day"><Moon size={25} strokeWidth={1}/><p>No plans on {formatDate(selected,{weekday:'long'})}.</p><Action onClick={openAdd}>Add something <Plus size={15}/></Action></div>}</div><div className="panel-note"><span className="tiny-line"/>Only the plans you’ve confirmed.</div></section>;
 const header=<header className="app-header">{brand}<nav className="app-links" aria-label="Calendar navigation"><span className="active-link">Calendar</span>{reviewButton}</nav><div className="app-header-right"><Action onClick={()=>setModal('settings')} label="Calendar settings"><SlidersHorizontal size={18}/></Action><div className="avatar">R</div></div></header>;
 const title=<div className="month-heading"><div className="month-title"><span className="month-eyebrow">Your calendar</span><h1>{months[view.month]}<span>{view.year}</span></h1></div><div className="month-actions">{nav}{addButton}</div></div>;
 const weekStart=parseDate(selected);weekStart.setDate(weekStart.getDate()-(weekStart.getDay()+6)%7);
 const weekDates=Array.from({length:7},(_,i)=>{const d=new Date(weekStart);d.setDate(d.getDate()+i);return iso(d)});
 const weekEnd=parseDate(weekDates[6]);
 const crossesYear=weekStart.getFullYear()!==weekEnd.getFullYear();
 const crossesMonth=crossesYear||weekStart.getMonth()!==weekEnd.getMonth();
 const weekRange=`${formatDate(weekDates[0],{day:'numeric',month:crossesMonth?'short':undefined,year:crossesYear?'numeric':undefined})}–${formatDate(weekDates[6],{day:'numeric',month:crossesMonth?'short':'long',year:crossesYear?'numeric':undefined})}`;
 const weekAgenda=<aside className="week-agenda"><header className="week-agenda-heading"><span className="overline">Your week</span><h2>{weekRange}</h2></header><div className="week-agenda-list">{weekDates.map(date=>{const items=dayPlans(plans,date);return <section className={`agenda-day ${date===selected?'agenda-selected':''}`} key={date}><button className="agenda-date" onClick={()=>chooseDay(date)}><span>{formatDate(date,{weekday:'short'})}</span><strong>{parseDate(date).getDate()}</strong></button><div className="agenda-day-plans">{items.length?items.map(p=><button className={`week-plan kind-${p.kind}`} key={p.id} onClick={()=>openPlan(p)}><span className="week-plan-time">{p.endDate===date?'Checkout':p.time?`${p.time}${p.zoneLabel?` · ${p.zoneLabel}`:''}`:p.kind==='stay'?'Stay':'Time not supplied'}</span><strong>{p.title}</strong></button>):<span className="week-free">No plans</span>}</div></section>})}</div></aside>;
 const r2Header=<header className="r2-header"><div className="r2-wordmark"><CalendarDays size={21} strokeWidth={1.4}/><span>{['air','focus','flow'].includes(style)?'field':'contour'}<i>.</i></span></div><div className="r2-header-links"><span className="current-view">Calendar</span>{reviewButton}</div><div className="r2-header-end"><Action onClick={()=>setModal('settings')} label="Settings"><SlidersHorizontal size={18}/></Action><span className="avatar">R</span></div></header>;
 const r2Month=<div className="r2-month-heading"><div className="r2-month-name"><h1>{months[view.month]}<span>{view.year}</span></h1><span className="r2-month-meta">Personal calendar</span></div>{nav}<div className="r2-month-end">{addButton}</div></div>;
 const r2Rail=<aside className="r2-rail"><span className="r2-rail-mark"><CalendarDays size={24} strokeWidth={1.4}/></span><span className="r2-rail-active"><CalendarDays size={20}/><span className="sr-only">Calendar</span></span><button onClick={()=>setModal('review')} aria-label={`Review ${suggestions.length} suggestions`}><Inbox size={20}/><small>{suggestions.length}</small></button><button className="r2-rail-settings" onClick={()=>setModal('settings')} aria-label="Settings"><SlidersHorizontal size={19}/></button></aside>;
 const iteration=isNew?<>
 {style==='air'&&<div className="r2-layout air-layout">{r2Header}{r2Month}<div className="air-month">{calendar}</div><div className="air-agenda">{dayPanel}</div><footer className="r2-foot"><span>{total} plans this month</span><span>Europe/London</span></footer></div>}
 {style==='focus'&&<div className="r2-layout focus-layout">{r2Header}<div className="focus-body"><div className="focus-month">{r2Month}{calendar}</div><div className="focus-day"><div className="focus-day-label"><span>Day overview</span><Clock3 size={15}/></div>{dayPanel}</div></div><footer className="r2-foot"><span>Personal calendar</span><span>Europe/London</span></footer></div>}
 {style==='flow'&&<div className="r2-layout flow-layout">{r2Header}{r2Month}<div className="flow-body"><div className="flow-month">{calendar}<div className="flow-key"><span><i/>Selected day</span><span>{total} plans this month</span></div></div>{weekAgenda}</div></div>}
 {style==='slate'&&<div className="r2-layout slate-layout">{r2Header}{r2Month}<div className="slate-body">{calendar}{dayPanel}</div><footer className="r2-foot"><span>Personal calendar</span><span>Europe/London</span></footer></div>}
 {style==='edge'&&<div className="edge-layout">{r2Rail}<div className="edge-content"><div className="edge-mobile-header">{r2Header}</div>{r2Month}<div className="edge-month">{calendar}{peekOpen?<div className={`edge-peek ${(parseDate(selected).getDay()+6)%7>=3?'peek-left':''}`}><button className="peek-close" ref={peekCloseRef} onClick={()=>togglePeek(false)} aria-label="Close day details"><X size={17}/></button>{dayPanel}</div>:<button className="edge-reopen" ref={peekReopenRef} onClick={()=>togglePeek(true)} aria-label="Open selected day details"><span>{formatDate(selected,{weekday:'short',day:'numeric',month:'short'})}</span><b>{entries.length} {entries.length===1?'plan':'plans'}</b><ArrowUpRight size={16}/></button>}</div><footer className="r2-foot"><span>{total} plans this month</span><span>Europe/London</span></footer></div></div>}
 </>:null;
 return <div className="design-studio"><header className="studio-toolbar"><div className="studio-title"><span className="studio-emblem">c</span><span>Calendar studies<small>{isNew?'Field + Contour, refined.':'The original five.'}</small></span></div><div className="round-switch" aria-label="Design round"><button aria-pressed={!isNew} onClick={()=>switchStyle('field')}>Originals</button><button aria-pressed={isNew} onClick={()=>switchStyle('air')}>Round 2</button></div><nav className="study-tabs" aria-label="Choose design">{visibleStudies.map(s=><button key={s.id} aria-pressed={style===s.id} onClick={()=>switchStyle(s.id)} className={style===s.id?'active':''}><span style={{background:s.color}} className="study-swatch"/><b>{s.letter}</b><span>{s.name}</span></button>)}</nav><div className="studio-tools"><button onClick={()=>setPhone(!phone)} aria-label={phone?'Desktop preview':'Phone preview'} title={phone?'Desktop preview':'Phone preview'}>{phone?<Monitor size={18}/>:<Smartphone size={18}/>}</button><button onClick={reset} aria-label="Reset sample plans" title="Reset sample plans"><RotateCcw size={17}/></button><button className="feedback-button" onClick={()=>setModal('notes')}>Notes <span>{Object.values(notes).filter(Boolean).length||''}</span></button></div></header><div className={`preview-stage ${phone?'phone-stage':''}`}><div className={`preview-viewport ${phone?'phone-preview':''}`}><main className={`calendar-app theme-${style} ${isNew?'round-two':''}`}>
 {isNew?iteration:style==='contour'?<><aside className="navigation-rail"><div className="rail-logo"><CalendarDays size={25} strokeWidth={1.4}/></div><button className="rail-active" aria-label="Calendar"><CalendarDays size={21}/></button><button onClick={()=>setModal('review')} aria-label={`Review ${suggestions.length} suggestions`}><Inbox size={21}/><i>{suggestions.length}</i></button><div className="rail-bottom"><button onClick={()=>setModal('settings')} aria-label="Settings"><SlidersHorizontal size={20}/></button><div className="avatar">R</div></div></aside><div className="contour-workspace"><header className="contour-header"><div className="breadcrumb">Personal <span>/</span> Calendar</div>{reviewButton}</header>{title}<div className="month-and-day">{calendar}{dayPanel}</div><footer className="app-foot"><span><i className="status-dot"/>Sample calendar</span><span>Europe/London</span></footer></div></>:
 style==='margin'?<div className="margin-layout">{header}<div className="margin-heading"><div><div className="month-eyebrow">Personal calendar</div><h1>{months[view.month]}<span>{view.year}</span></h1></div><div className="month-actions">{nav}{addButton}</div></div>{calendar}{dayPanel}</div>:
 style==='gather'?<div className="gather-layout">{header}<div className="gather-title"><span className="month-eyebrow">Your calendar</span><h1>{months[view.month]}<span>{view.year}</span></h1>{nav}</div><div className="gather-calendar">{calendar}</div>{dayPanel}<div className="gather-add">{addButton}</div></div>:
 style==='field'?<div className="field-layout">{header}<div className="field-heading"><h1>{months[view.month]} <span>{view.year}</span></h1>{nav}<span className="field-zone">Europe/London</span>{addButton}</div>{calendar}{dayPanel}<footer className="app-foot"><span>{total} plans this month</span><span>Europe/London</span></footer></div>:
 <div className="ember-layout">{header}<div className="ember-heading"><div><span className="month-eyebrow">Your calendar</span><h1>{months[view.month]}<span>{view.year}</span></h1></div>{nav}{addButton}</div><div className="ember-body">{calendar}{dayPanel}</div><div className="ember-footer"><span>{total} plans this month</span><span>Europe/London</span></div></div>}
 </main></div></div><footer className="studio-footer"><span><b>{study.letter} / {study.name}</b><span className="footer-description">{study.focus}</span></span><span className="sample-label">Fictional plans · click a date or open Review</span><button className={liked.includes(style)?'is-liked':''} onClick={toggleLike}>{liked.includes(style)?<Check size={15}/>:<Plus size={15}/>} {liked.includes(style)?'Shortlisted':'Shortlist'}</button></footer>
 <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className={`mock-dialog theme-${style} ${phone?'phone-dialog':''}`}><DialogTitle className="dialog-title">{modal==='review'?'A few things to look at':modal==='event'?active?.title:modal==='add'?'Add a plan':modal==='notes'?`Your notes on ${study.name}`:'Calendar settings'}</DialogTitle><DialogDescription className="dialog-description">{modal==='review'?'You decide what becomes a plan.':modal==='event'?'Booking details · fictional example':modal==='add'?'This creates a sample event in the mockup.':modal==='notes'?'Keep what you like. Tell us what feels off.':'Preview preferences and sample connections.'}</DialogDescription>
 {modal==='review'&&<div className="review-list">{suggestions.length?suggestions.map(s=><article className="suggestion" key={s.id}><div className="suggestion-top"><span className="source-tag">{s.plan.source}</span><span>{s.status}</span></div><h3>{s.plan.title}</h3><p className="suggestion-date">{s.plan.date?formatDate(s.plan.date):'Date to confirm'} · {s.plan.time}</p><details><summary>View message</summary><blockquote>{s.excerpt}</blockquote></details>{s.needsDate&&<label className="field-label" htmlFor="suggestion-date">Which date?<Input id="suggestion-date" type="date" value={dateChoice} onChange={e=>setDateChoice(e.target.value)}/><small>The forward didn’t include the original message date.</small></label>}<div className="suggestion-actions"><Button className="primary-action" onClick={()=>accept(s)} disabled={s.needsDate&&!dateChoice}>{s.action}<Check size={16}/></Button><Action onClick={()=>{setSuggestions(prev=>prev.filter(x=>x.id!==s.id));setNotice('Suggestion dismissed')}}>Dismiss</Action></div>{s.id==='party'&&<small className="quiet-note">Adds to your calendar. No RSVP is sent.</small>}</article>):<div className="review-empty"><Check size={30}/><h3>Everything is in its place.</h3><p>No suggestions left to review.</p><Action onClick={()=>setModal(null)}>Back to calendar <ArrowRight size={16}/></Action></div>}</div>}
 {modal==='event'&&active&&<div className="event-modal"><div className={`event-modal-icon kind-${active.kind}`}><Icon kind={active.kind} title={active.title} size={28}/></div><div className="booking-line"><CalendarDays size={18}/><span>{formatDate(active.date)}{active.endDate?` – ${formatDate(active.endDate,{day:'numeric',month:'long'})}`:''}</span></div><div className="booking-line"><Clock3 size={18}/><span>{active.time?`${active.time}${active.endTime?` – ${active.endTime}`:''}`:'Time not supplied'}{active.time?` · ${active.zoneLabel||'London'} time`:''}</span></div><div className="booking-line"><MapPin size={18}/><span>{active.location}</span></div><p className="booking-detail">{active.detail}</p>{active.reference&&<button className="reference" onClick={()=>copy(active.reference!)}><span>Booking reference<strong>{active.reference}</strong></span><Copy size={18}/></button>}<div className="booking-source"><span>From {active.source}</span><span><Check size={14}/> On your calendar</span></div><Action onClick={()=>{setPlans(prev=>prev.filter(p=>p.id!==active.id));setModal(null);setNotice('Removed from calendar')}}>Remove from calendar</Action></div>}
 {modal==='add'&&<form className="add-form" onSubmit={saveDraft}><label className="field-label" htmlFor="plan-title">What’s the plan?<Input id="plan-title" required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Dinner, a trip, a good catch-up…"/></label><div className="form-pair"><label className="field-label" htmlFor="plan-date">Date<Input id="plan-date" required type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label className="field-label" htmlFor="plan-time">Time · optional<Input id="plan-time" type="time" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label></div><label className="field-label" htmlFor="plan-location">Location<Input id="plan-location" value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="Add a place"/></label><p className="quiet-note">Leave the time empty if it hasn’t been agreed.</p><Button className="primary-action" type="submit">Add to calendar <Plus size={17}/></Button></form>}
 {modal==='notes'&&<div className="notes-form"><div className="note-swatch" style={{background:study.color}}/><p>{study.focus}</p><Textarea aria-label={`Notes on ${study.name}`} value={notes[style]||''} onChange={e=>saveNote(e.target.value)} placeholder="The grid feels good, but I’d change…" rows={6}/><span className="quiet-note">Saved in this browser. Nothing is sent.</span><Action primary onClick={()=>copy(studies.map(s=>`${s.letter}. ${s.name}${liked.includes(s.id)?' [shortlisted]':''}\n${notes[s.id]||'No notes yet.'}`).join('\n\n'))}>Copy all feedback <Copy size={16}/></Action></div>}
 {modal==='settings'&&<div className="settings-list"><div><span>Time zone</span><strong>Europe/London</strong></div><div><span>Week starts</span><strong>Monday</strong></div><div><span>Default reminder</span><strong>15 minutes before</strong></div><div><span>Gmail</span><strong>Sample account</strong></div><div><span>WhatsApp</span><strong>Sample messages</strong></div><p>These mockups use fictional bookings. No accounts are connected, messages sent, or reminders scheduled.</p><Action onClick={()=>{reset();setModal(null)}}>Reset sample plans <RotateCcw size={16}/></Action></div>}
 </DialogContent></Dialog>{notice&&<output className="notice" aria-live="polite"><Check size={16}/>{notice}</output>}
 </div>;
}
